python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./check96/ --data_path PEMS04.npz --model_id PEMS04 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 307 --dec_in 307 --c_out 307 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 128 --learning_rate 0.002 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method conv --down_sampling_window 2 --gpu 2 --op_num 4
python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./check96/ --data_path PEMS07.npz --model_id PEMS07 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 883 --dec_in 883 --c_out 883 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 256 --d_ff 512 --batch_size 128 --learning_rate 0.002 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 2 --op_num 3 --seed 96
python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./check96/ --data_path PEMS07.npz --model_id PEMS07 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 883 --dec_in 883 --c_out 883 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 256 --d_ff 512 --batch_size 64 --learning_rate 0.005 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 2 --op_num 3 --seed 96
python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./check96/ --data_path PEMS08.npz --model_id PEMS08 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 4 --d_layers 1 --factor 3 --enc_in 170 --dec_in 170 --c_out 170 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 40 --d_ff 160 --batch_size 64 --learning_rate 0.0045 --train_epochs 25 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 2 --op_num 2 
python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./check96/ --data_path PEMS08.npz --model_id PEMS08 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 4 --d_layers 1 --factor 3 --enc_in 170 --dec_in 170 --c_out 170 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 128 --learning_rate 0.002 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 2 --op_num 2 
python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./check96/ --data_path PEMS03.npz --model_id PEMS03 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 358 --dec_in 358 --c_out 358 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 64 --learning_rate 0.0005 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 2 --op_num 2 --seed 42
python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./check96/ --data_path PEMS03.npz --model_id PEMS03 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 2 --factor 3 --enc_in 358 --dec_in 358 --c_out 358 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 64 --learning_rate 0.0005 --train_epochs 20 --patience 10 --down_sampling_layers 3 --down_sampling_method avg --down_sampling_window 2 --gpu 2 --op_num 2 --seed 42

# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./check96/ --data_path PEMS03.npz --model_id PEMS03 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 2 --factor 3 --enc_in 358 --dec_in 358 --c_out 358 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 64 --learning_rate 0.0005 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 3 --op_num 2 --seed 42
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./check96/ --data_path PEMS03.npz --model_id PEMS03 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 358 --dec_in 358 --c_out 358 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 64 --learning_rate 0.0005 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 3 --op_num 2 --seed 42

# python -u main.py --is_training 0 --root_path ./dataset/PEMS/ --checkpoints ./check96/ --data_path PEMS03.npz --model_id PEMS03 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 358 --dec_in 358 --c_out 358 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 64 --learning_rate 0.0005 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 2 --op_num 2 --seed 42

# # wo dep
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkwo/ --data_path PEMS03.npz --model_id PEMS03 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 358 --dec_in 358 --c_out 358 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 64 --learning_rate 0.0005 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 4 --op_num 2 --seed 42
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkwo/ --data_path PEMS04.npz --model_id PEMS04 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 307 --dec_in 307 --c_out 307 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 128 --learning_rate 0.002 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 4 --op_num 4
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkwo/ --data_path PEMS07.npz --model_id PEMS07 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 883 --dec_in 883 --c_out 883 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 256 --d_ff 512 --batch_size 128 --learning_rate 0.002 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 3 --op_num 3 --seed 96
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkwo/ --data_path PEMS08.npz --model_id PEMS08 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 4 --d_layers 1 --factor 3 --enc_in 170 --dec_in 170 --c_out 170 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 40 --d_ff 160 --batch_size 64 --learning_rate 0.0045 --train_epochs 25 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 1 --op_num 2 

# #wo fu
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkwo1/ --data_path PEMS03.npz --model_id PEMS03 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 358 --dec_in 358 --c_out 358 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 64 --learning_rate 0.0005 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 4 --op_num 2 --seed 42
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkwo1/ --data_path PEMS04.npz --model_id PEMS04 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 307 --dec_in 307 --c_out 307 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 128 --learning_rate 0.002 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 4 --op_num 4
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkwo1/ --data_path PEMS07.npz --model_id PEMS07 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 883 --dec_in 883 --c_out 883 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 256 --d_ff 512 --batch_size 128 --learning_rate 0.002 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 5 --op_num 3 --seed 96
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkwo1/ --data_path PEMS08.npz --model_id PEMS08 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 4 --d_layers 1 --factor 3 --enc_in 170 --dec_in 170 --c_out 170 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 40 --d_ff 160 --batch_size 64 --learning_rate 0.0045 --train_epochs 25 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 1 --op_num 2 

# #wo pre
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkwop/ --data_path PEMS03.npz --model_id PEMS03 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 358 --dec_in 358 --c_out 358 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 64 --learning_rate 0.0005 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 4 --op_num 2 --seed 42
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkwop/ --data_path PEMS04.npz --model_id PEMS04 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 307 --dec_in 307 --c_out 307 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 128 --learning_rate 0.002 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 4 --op_num 4
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkwop/ --data_path PEMS07.npz --model_id PEMS07 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 883 --dec_in 883 --c_out 883 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 256 --d_ff 512 --batch_size 128 --learning_rate 0.002 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 5 --op_num 3 --seed 96
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkwop/ --data_path PEMS08.npz --model_id PEMS08 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 4 --d_layers 1 --factor 3 --enc_in 170 --dec_in 170 --c_out 170 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 40 --d_ff 160 --batch_size 64 --learning_rate 0.0045 --train_epochs 25 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 1 --op_num 2 


# #wo multi-scale layer
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkwom/ --data_path PEMS03.npz --model_id PEMS03 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 358 --dec_in 358 --c_out 358 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 64 --learning_rate 0.0005 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 4 --op_num 2 --seed 42
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkwom/ --data_path PEMS04.npz --model_id PEMS04 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 307 --dec_in 307 --c_out 307 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 128 --learning_rate 0.002 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 4 --op_num 4
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkwom/ --data_path PEMS07.npz --model_id PEMS07 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 883 --dec_in 883 --c_out 883 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 256 --d_ff 512 --batch_size 128 --learning_rate 0.002 --train_epochs 20 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 5 --op_num 3 --seed 96
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkwom/ --data_path PEMS08.npz --model_id PEMS08 --model AutoMixer --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 4 --d_layers 1 --factor 3 --enc_in 170 --dec_in 170 --c_out 170 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 40 --d_ff 160 --batch_size 64 --learning_rate 0.0045 --train_epochs 25 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 1 --op_num 2 



# # autostg
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkautostg/ --data_path PEMS03.npz --model_id PEMS03 --model Autostg --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 358 --dec_in 358 --c_out 358 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 16 --learning_rate 0.0005 --train_epochs 70 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 4 --op_num 2 
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkautostg/ --data_path PEMS04.npz --model_id PEMS04 --model Autostg --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 307 --dec_in 307 --c_out 307 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 128 --d_ff 256 --batch_size 128 --learning_rate 0.002 --train_epochs 70 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 4 --op_num 4 
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkautostg/ --data_path PEMS07.npz --model_id PEMS07 --model Autostg --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 5 --d_layers 1 --factor 3 --enc_in 883 --dec_in 883 --c_out 883 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 256 --d_ff 512 --batch_size 128 --learning_rate 0.002 --train_epochs 70 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 5 --op_num 3 
# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkautostg/ --data_path PEMS08.npz --model_id PEMS08 --model Autostg --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 4 --d_layers 1 --factor 3 --enc_in 170 --dec_in 170 --c_out 170 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 40 --d_ff 160 --batch_size 64 --learning_rate 0.0045 --train_epochs 70 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 1 --op_num 2



# python -u main.py --is_training 1 --root_path ./dataset/PEMS/ --checkpoints ./checkautostg/ --data_path PEMS08.npz --model_id PEMS08 --model Autostg --data PEMS --features M --seq_len 96 --label_len 0 --pred_len 12 --e_layers 4 --d_layers 1 --factor 3 --enc_in 170 --dec_in 170 --c_out 170 --des 'Exp' --itr 1 --use_norm 0  --channel_independence 0 --d_model 40 --d_ff 160 --batch_size 64 --learning_rate 0.0045 --train_epochs 70 --patience 10 --down_sampling_layers 2 --down_sampling_method avg --down_sampling_window 2 --gpu 5 --op_num 2 
